<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "\n";
echo "<head>\n";
echo "    <title> HELNA FREECENTA</title>\n";
echo "    <style type=\"text/css\"></style>\n";
echo "    <link rel=\"stylesheet\" type=\"text/css\" href=\"960_16_col.css\">\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "    <div class=\"container_16\" ;>\n";
echo "        <div class=\"grid_16 a\" style=\"background-color: #fdeff4;\">\n";
echo "            <b><font face=\"Vladimir Script\" , font size=\"16\"> Helna Freecenta</font></b>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div class=\"container_16\">\n";
echo "        <div class=\"grid_6 a\" style=\"background-color: #fff5ee; margin-top: 80px\" ;>\n";
echo "            <b><font face=\"Freestyle Script\" , font size=\"6\"> About Me </font></b>\n";
echo "            <img src=\"information-management.png\" width=50px, height=50px, align=\"left\">\n";
echo "            <br/>\n";
echo "            <br/> Lahir di Malang pada tanggal 24 Januari 2001\n";
echo "            <br/> Anak ke 3 dari 3 bersaudara\n";
echo "            <br/> Sedang menempuh kuliah di UPN JATIM\n";
echo "            <br/> Jurusan Teknik Informatika\n";
echo "        </div>\n";
echo "        <div class=\"grid_4 lingkaran1\">\n";
echo "            <img class=\"rounded-image\" src=\"IMG_0345.JPG\" width=200px, height=200px />\n";
echo "        </div>\n";
echo "        <div class=\"grid_6 a \" style=\"background-color: #fff5ee; margin-top: 20px\" ;>\n";
echo "            <b><font face=\"Freestyle Script\" , font size=\"6\"> Contact Me </font></b>\n";
echo "            <br/> <img src=\"google-plus.png\" width=20px, height=20px;> hlnfrcnt@gmail.com\n";
echo "            <br/> <img src=\"instagram.png\" width=20px, height=20px;> helnafrcnt\n";
echo "            <br/> <img src=\"whatsapp.png\" width=20px, height=20px;> 085853829631\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div class=\"container_16\" ;>\n";
echo "        <div class=\"grid_7 a\" style=\"background-color: #fce3e1; margin-top: 80px;margin-left:40px\" ;>\n";
echo "            <b><font face=\"Freestyle Script\" , font size=\"6\"> Experience</font></b>\n";
echo "            <img src=\"experiment-results.png\" width=50px, height=50px, align=\"left\">\n";
echo "            <br/>\n";
echo "            <br/> OSIS SMP 1 Singosari\n";
echo "            <br/> OSIS SMAN 1 Lawang\n";
echo "        </div>\n";
echo "        <div class=\"grid_2\">\n";
echo "        </div>\n";
echo "        <div class=\"grid_7 push_1 a\" style=\"background-color: #fce3e1; margin-top: 10px\" ;>\n";
echo "            <b><font face=\"Freestyle Script\" , font size=\"6\"> Education</font></b>\n";
echo "            <img src=\"school.png\" width=50px, height=50px, align=\"left\">\n";
echo "            <br/>\n";
echo "            <br/> TK Dharma Wanita\n";
echo "            <br/> SDN Lawang 03\n";
echo "            <br/> SMPN 1 Singosari\n";
echo "            <br/> SMAN 1 Lawang\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div class=\"container_16\" ;>\n";
echo "        <div class=\"grid_16 a\" style=\"background-color: #bd908f; margin-top:30px\" ;>\n";
echo "            <b><font face=\"Freestyle Script\" , font size=\"10\"> Skill</font></b>\n";
echo "            <br/> <img src=\"cooking-pots.png\" width=50px, height=50px;>\n";
echo "            <td><img src=\"violin.png\" width=50px, height=50px;></td>\n";
echo "            <td> <img src=\"office.png\" width=50px, height=50px;></td>\n";
echo "            <td> <img src=\"english.png\" width=50px, height=50px;></td>\n";
echo "            <td> <img src=\"singing.png\" width=50px, height=50px;></td>\n";
echo "            <td> <img src=\"group.png\" width=50px, height=50px;></td>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "</body>\n";
echo "\n";
echo "</html>\n";
?>